
debug: false
env: prod

info:
  version: "1.0.0"
  type: "router"

localFiles:
  keys: "keys.json"
  contract: "contract.json"
  init: "init.json"

timeout:
  alive: 10s # alive interval
  coala: 3m  # timeout for coala requests
  registerRepeat: 24h # period for registration repeat

masterNodes:
  - 157.245.57.218:5683
  - 188.166.71.64:5683
  - 192.81.216.57:5683

everscale:
  elector: "0:b503542d5a02efda094b467c7503dde55e35f6488033efdae914db10f7dd2789"
  vendor: "0:041c0970f0de1f40a05f98e6659510fa6df85c78a45611f1b5a1635fa79dd9ab"
  deviceAPI: "0:ac89285c69ebf4748d04a3a19bc8f831ef3cda7954d10a4c76465dcd06a82691"