prod:
  hosts:
    device1:
      ansible_host: 144.126.201.225
      port: 5684
#    device2:
#      ansible_host: 144.126.201.225
#      port: 5685
#    device3:
#      ansible_host: 144.126.201.225
#      port: 5686

  ##################################################
  vars:
    service: device
    config: prod
    PROJECTPATH: ../../
    DEPLOYROOT: /opt/everiot
    BuildBin: device_bin
    monit_alert: sp@golbex.com # адрес для монита
    ansible_ssh_user: root
    GOOS: linux
    GOARCH: amd64
    CGO: 0